# Generated by Django 2.2.9 on 2019-12-27 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptowallet', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
