# Generated by Django 2.2.9 on 2019-12-30 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptowallet', '0005_auto_20191227_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='slug',
        ),
    ]
